apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-external-secret
  namespace: renovate
  spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_PAT
      remoteRef:
        key: renovate
        property: credential
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
