ingressClass:
  enabled: true 
  isDefaultClass: false 
  name: internal

providers:
  kubernetesIngress:
    enabled: true 
    ingressClass: internal 
    publishedService:
      enabled: true 
  kubernetesCRD:
    enabled: true 
    labelSelector: "traefik-instance=internal"


service:
  type: LoadBalancer 
  spec:
    loadBalancerClass: tailscale 
  annotations:
    tailscale.com/hostname: k8s-internal
