apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-elijahfyi
  namespace: traefik-internal
spec:
  secretName: wildcard-elijah-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "internal.elijah.fyi"
    - "*.internal.elijah.fyi"
