apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-public
  labels:
    traefik-instance: public
spec:
  defaultCertificate:
    secretName: wildcard-elijah-tls
