apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluentbit-external-secret
  namespace: fluentbit
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: opensearch-fluent-bit-writer
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: opensearch-fluent-bit-writer
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: opensearch-fluent-bit-writer
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
