apiVersion: opensearch.org/v1
kind: OpensearchUserRoleBinding
metadata:
  name: fluent-bit
  namespace: opensearch
spec:
  opensearchCluster:
    name: burns
  users:
    - fluent-bit
  roles:
    - fluent-bit-writer
