apiVersion: opensearch.org/v1
kind: OpensearchUser
metadata:
  name: fluent-bit
  namespace: opensearch
spec:
  opensearchCluster:
    name: burns
  passwordFrom:
    name: opensearch-fluent-bit-writer
    key: password
  backendRoles: []
