apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-external-secret
  namespace: umami
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: umami-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "postgresql://{{ .postgresql_username }}:{{ .postgresql_password }}@{{ .postgresql_host }}:{{ .postgresql_port }}/{{ .postgresql_name }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: umami
        property: secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql_password
      remoteRef:
        key: umami
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql_host
      remoteRef:
        key: umami
        property: host
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql_port
      remoteRef:
        key: umami
        property: port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql_username
      remoteRef:
        key: umami
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql_name
      remoteRef:
        key: umami
        property: name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: username
      remoteRef:
        key: umami
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: umami
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
