apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-external-secret
  namespace: tailscale
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: operator-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-oidc
        property: client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: tailscale-oidc
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
