apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: argocd
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: argocd-oidc
        property: client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: argocd-oidc
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
