apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/cluster-secret-store/
    repoURL: https://gitlab.com/ej-platform/kubernetes/burns
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
