apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.58.1
      helm:
        valueFiles:
          - $values/configurations/fluentbit/values.yaml
    - repoURL: https://github.com/ej-east/burns
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ej-east/burns
      targetRevision: HEAD
      path: manifests/fluentbit
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fluentbit
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
        istio-injection: disabled
        external-secrets.elijah.fyi/onepassword: "enabled"
    automated:
      prune: true
      selfHeal: true
