apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://opensearch-project.github.io/opensearch-k8s-operator/
      chart: opensearch-operator
      targetRevision: 3.0.2
      helm:
        valueFiles:
          - $values/configurations/opensearch-operator/values.yaml
    - repoURL: https://github.com/ej-east/burns
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opensearch-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
