apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.102.3
      helm:
        valueFiles:
          - $values/configurations/tailscale/values.yaml
    - repoURL: https://github.com/ej-east/burns
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ej-east/burns
      targetRevision: HEAD
      path: manifests/tailscale
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        external-secrets.elijah.fyi/onepassword: "enabled"
        istio.io/dataplane-mode: ambient
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
