apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret
  namespace: gitlab-runner
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitlab-runner-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: runner-token
      remoteRef:
        key: gitlab-runner
        property: credential
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql_password
      remoteRef:
        key: runner-registration-token
        property: legacy
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
